---
driver:
  name: vagrant


provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: debian-7.8
  - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[site-cheftypo3org::default]
    attributes:
      chef-server:
        api_fqdn: 'localhost'
      site-cheftypo3org:
        ssl_certificate: wildcard.vagrant
    driver:
      network:
        - ['private_network', {ip: '192.168.243.6'}]
